---
title: "Reproducible Research: Peer Assessment 1"
output: 
   html_document: 
     keep_md: yes
---

## Loading and preprocessing the data
1. Download the [activity monitoring data](https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip) to my local hard drive.
2. Make sure that the working directory is correct. 
3. Import the data into R.
```{r getdata}
  #This is a one-time effort
  activity <- read.csv("Week2/activity.csv")
```


## What is mean total number of steps taken per day?
```{r total number of steps}
library(ggplot2)
library(tidyverse)
total.steps <- activity %>% group_by(date) %>% summarise(steps = sum(steps, na.rm = T))
#histogram
total.steps %>% ggplot(aes(x = steps)) + geom_histogram(binwidth=1000) + ggtitle("Total Number of Steps Taken Each Day") 
#mean
mean(total.steps$steps, na.rm=TRUE)
#median
median(total.steps$steps, na.rm=TRUE)

```


## What is the average daily activity pattern?
```{r daily average}
averages <- activity %>% group_by(interval) %>% summarise(avg = mean(steps, na.rm = TRUE))
#time series plot
averages %>% ggplot(aes(x=interval, y=avg)) +
    geom_line() +
    xlab("5-minute interval") +
    ylab("average number of steps taken")

#maximum number of steps
averages[which.max(averages$avg),]
```


## Imputing missing values

```{r missing values}
missing <- is.na(activity$steps)
# How many missing
table(missing)
#1. the total number of missing values in the dataset: 2304
```

```{r imputing_missing_values}
#2. Devise a strategy for filling in all of the missing values in the dataset.
#Replace each missing value with the mean value of its 5-minute interval

library(magrittr)
library(dplyr)

replacewithmean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
meandata <- activity %>% group_by(interval) %>% mutate(steps= replacewithmean(steps))
head(meandata)
filled.data <- aggregate(meandata$steps, by=list(meandata$date), sum)

names(filled.data)[1] ="date"
names(filled.data)[2] ="steps"
head(filled.data,15)

##Method 2. This works, but knitr can't generate the code. 
#a copy of the main dataset; the imputed steps will be included here
#filled.data <- activity
#vector of missing data
#missing.data <- filled.data[is.na(filled.data$steps),]
#fill.value <- function (steps, interval){ 
#  averages[averages$interval==interval, "steps"]
#  }
#missing.data$steps <- mapply(fill.value, missing.data$steps, missing.data$interval, SIMPLIFY = TRUE)


#filled.data$steps[is.na(filled.data$steps)] <- missing.data$steps
#filled.data
#As you can see, no missing data in the new dataset
#filled.data[is.na(filled.data$steps),]
```

```{r histogram, mean, and median of the new dataset}
total.steps2 <- filled.data %>% group_by(date) %>% summarise(steps = sum(steps, na.rm = T))
#histogram
total.steps2 %>% ggplot(aes(x = steps)) + geom_histogram(binwidth=1000) + ggtitle("Total Number of Steps Taken Each Day") 
#mean
mean(total.steps2$steps, na.rm=TRUE)
#median
median(total.steps2$steps, na.rm=TRUE)
#Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?
print("these values are higher than the first part of the assignment")
print("Imputing the missing data helps to fix the skewness of the data")
```


## Are there differences in activity patterns between weekdays and weekends?

```{r difference weekdays and weekends}
#1. Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.
meandata$date <- as.Date(meandata$date)
meandata$weekday <- weekdays(meandata$date)
meandata$weekend <- ifelse(meandata$weekday=="Saturday" | meandata$weekday=="Sunday", "Weekend", "Weekday" )

#2. Make a panel plot containing a time series plot (i.e. \color{red}{\verb|type = "l"|}type="l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.
meandataweekendweekday <- aggregate(meandata$steps , by= list(meandata$weekend, meandata$interval), na.omit(mean))
names(meandataweekendweekday) <- c("weekend", "interval", "steps")

ggplot(meandataweekendweekday, aes(x=interval, y=steps, color=weekend)) + geom_line()+
facet_grid(weekend ~.) + xlab("Interval") + ylab("Mean of Steps") +
    ggtitle("Comparison of Average Number of Steps in Each Interval")
```

